### ISSUE TITLE
Rejecting a URl and all it's nested URLS

### ISSUE THREAD

**Issue by ZeroByter** [brillout/vite-plugin-ssr#243]
Hey, I really like this library, can't imagine not developing a website in the future without this library, but I have a simple question.

Let's say I have the following pages domain setup
/admin
/admin/users

```
root:
 - pages:
   - admin:
     - pages:
       - index:
         - index.page.jsx
         - index.page.route.js
       - users:
         - index.page.jsx
   - ... other pages ...
```

in `/pages/admin/pages/index/index.page.route.js`:
```js
import { isUserAdmin } from "../../../../server/essentials"

export default ({ pageContext }) => {
    if (!isUserAdmin(pageContext.user)) return false

    return true
}
```

This setup works great for limiting non-admin users from reaching index.js (path /admin), but they can still reach /admin/users
Other than creating the same index.page.route.js for each sub-URL in /admin, is there a way that the `index.page.route.js` can block access to all nested URLs?

I also tried several variations of the file structure and putting different things in the index.page.route.js (of both the index file, and the users file) but no luck.
