### ISSUE TITLE
CSS loading in development upon browser back/forward buttons

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#401]
### Description

This is fixed already. This is for reference.

`http://localhost:3000/renderer/PageShell.css` sometimes return the following. (Depending on the HTTP request headers.)

```js
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/renderer/PageShell.css");import { updateStyle as __vite__updateStyle, removeStyle as __vite__removeStyle } from "/@vite/client"
const __vite__id = "/home/romuuu/tmp/vite-ssr-project/renderer/PageShell.css"
const __vite__css = "/* This CSS is common to all pages */\n\nbody {\n  margin: 0;\n  font-family: sans-serif;\n}\n* {\n  box-sizing: border-box;\n}\na {\n  text-decoration: none;\n}\n\n.navitem {\n  padding: 3px 10px;\n}\n.navitem.is-active {\n  background-color: #eee;\n}\n"
__vite__updateStyle(__vite__id, __vite__css)
import.meta.hot.accept()
export default __vite__css
import.meta.hot.prune(() => __vite__removeStyle(__vite__id))
```

Which makes the browser choke when loaded via `<link rel="stylesheet" type="text/css" href="/renderer/PageShell.css">`.

Upon the user clicking on the back/forward button, the wrong HTTP headers are sent, and the browser chokes.

The solution is to append the `?direct` suffix: `http://localhost:3000/renderer/PageShell.css?direct` always returns the following.

```css
/* This CSS is common to all pages */

body {
  margin: 0;
  font-family: sans-serif;
}
* {
  box-sizing: border-box;
}
a {
  text-decoration: none;
}

.navitem {
  padding: 3px 10px;
}
.navitem.is-active {
  background-color: #eee;
}
``` 

So we always use the `?direct` suffix when loading via HTML tags, e.g. `<link rel="stylesheet" type="text/css" href="/renderer/PageShell.css?direct">` instead of `<link rel="stylesheet" type="text/css" href="/renderer/PageShell.css">`.
